Fix Hungarian default date format and add Hungarian translations
macmotp/locale pull request #1
Opened 2024-09-25 07:53 UTC by tamasori

Hey,

I fixed the Hungarian default date format as it was incorrect, you can find more information here:
https://en.wikipedia.org/wiki/Date_and_time_notation_in_Hungary#Date

Also I added translations for the Hungarian language!

2024-09-26 10:35 UTC, mihaituhari requested changes
👋  I noticed a typo

2024-09-26 10:35 UTC, mihaituhari commented on src/Countries/Support/Translations/hu.php
> + * English
**issue:** 
```suggestion
 * Hungarian
```

2024-09-27 10:42 UTC, macmotp commented
Thank you @tamasori, since I am going to release a more stable version soon, I will keep this PR on hold and apply your changes directly. I will add you as contributor for reference

2024-09-28 12:37 UTC, tamasori commented
Ok, thank you @macmotp

2024-10-03 03:08 UTC, macmotp commented
All your changes have been included into the new release, thanks!

2024-10-03 03:08 UTC, closed without merging